### PR TITLE
Decouple gnu compiler/flags from cmake infrastructure, update readme,…

### PR DESCRIPTION
**Pull request by BrodyWilliams**
… remove unreachable break statements from -Wall, workaround from #atomic capture += 0 (immediate) with some compilers, minor qol adjustments

### CODE REVIEW

**Comment by jleidel** [comment]
you broke the build

**Comment by BrodyWilliams** [comment]
What issue(s) are you seeing? If there are any CI/CD tools coupled to the repo, I can't seem to locate them/the output. 

The only change of note here was to remove the gcc specific flags in favor of having the user supply them for their chosen compiler via -DCT_CFLAGS, -DCT_CXXFLAGS, and -DCT_LINKER_FLAGS.

The motivation for the above was that I needed to test the OpenMP offloading and OpenACC backends for Michael/Pedro, but none of the systems I have access to have offloading integrated into their gnu compilers. Others compilers did support it. Since users may run into similar issues or want to use something other than gcc it seemed like a better option to make things more generalizable.

Having said that, if you have some local script testing the builds, it will likely affect things since -fopenmp/etc. are no longer added by default.

**Comment by jleidel** [comment]
`cmake -DENABLE_OMP=ON ../` on Ubuntu 20.04 reveals the following.  The same thing errors out on OSX, Ubuntu 18.04, Ubuntu 16.06, Centos 7/8, etc.  
```
[ 20%] Building CXX object src/CircusTent/Impl/CT_OMP/CMakeFiles/CT_OMP_OBJS.dir/CT_OMP.cpp.o
[ 40%] Building C object src/CircusTent/Impl/CT_OMP/CMakeFiles/CT_OMP_OBJS.dir/CT_OMP_IMPL.c.o
[ 40%] Built target CT_OMP_OBJS
Scanning dependencies of target circustent
[ 60%] Building CXX object src/CircusTent/CMakeFiles/circustent.dir/CT_Main.cpp.o
[ 80%] Building CXX object src/CircusTent/CMakeFiles/circustent.dir/CTOpts.cpp.o
[100%] Linking CXX executable circustent
/usr/bin/ld: Impl/CT_OMP/CMakeFiles/CT_OMP_OBJS.dir/CT_OMP.cpp.o: in function `CT_OMP::AllocateData(unsigned long, unsigned long, unsigned long, unsigned long)':
CT_OMP.cpp:(.text+0x1d1): undefined reference to `omp_set_num_threads'
/usr/bin/ld: CT_OMP.cpp:(.text+0x1ee): undefined reference to `omp_get_num_threads'
/usr/bin/ld: Impl/CT_OMP/CMakeFiles/CT_OMP_OBJS.dir/CT_OMP_IMPL.c.o: in function `RAND_ADD':
CT_OMP_IMPL.c:(.text+0x12): undefined reference to `omp_get_thread_num'
/usr/bin/ld: Impl/CT_OMP/CMakeFiles/CT_OMP_OBJS.dir/CT_OMP_IMPL.c.o: in function `RAND_CAS':
CT_OMP_IMPL.c:(.text+0x62): undefined reference to `omp_get_thread_num'
/usr/bin/ld: Impl/CT_OMP/CMakeFiles/CT_OMP_OBJS.dir/CT_OMP_IMPL.c.o: in function `STRIDE1_ADD':
CT_OMP_IMPL.c:(.text+0xc1): undefined reference to `omp_get_thread_num'
/usr/bin/ld: Impl/CT_OMP/CMakeFiles/CT_OMP_OBJS.dir/CT_OMP_IMPL.c.o: in function `STRIDE1_CAS':
CT_OMP_IMPL.c:(.text+0x111): undefined reference to `omp_get_thread_num'
/usr/bin/ld: Impl/CT_OMP/CMakeFiles/CT_OMP_OBJS.dir/CT_OMP_IMPL.c.o: in function `STRIDEN_ADD':
CT_OMP_IMPL.c:(.text+0x162): undefined reference to `omp_get_thread_num'
/usr/bin/ld: Impl/CT_OMP/CMakeFiles/CT_OMP_OBJS.dir/CT_OMP_IMPL.c.o:CT_OMP_IMPL.c:(.text+0x1b2): more undefined references to `omp_get_thread_num' follow
collect2: error: ld returned 1 exit status
make[2]: *** [src/CircusTent/CMakeFiles/circustent.dir/build.make:103: src/CircusTent/circustent] Error 1
make[1]: *** [CMakeFiles/Makefile2:378: src/CircusTent/CMakeFiles/circustent.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Build step 'Execute shell' marked build as failure
Sending e-mails to: jleidel@tactcomplabs.com
[Set GitHub commit status (universal)] PENDING on repos [] (sha:5f4f8b8) with context:CircusTent/label_exp=ubuntu2004
Finished: FAILURE
```

**Comment by BrodyWilliams** [comment]
That makes sense, but, assuming CC=gcc CXX=g++,  does it work with "cmake -DENABLE_OMP=ON -DCT_LINKER_FLAGS="-fopenmp" ../" for example? I updated the readme step 3 to reflect this approach. Admittedly, the added versatility necessitates a bit more in terms of verboseness, but it seemed worth it rather than have the user edit the CMake files.

[brodyw@tessa003 build]$ cmake -DENABLE_OMP=ON -DCT_LINKER_FLAGS="-fopenmp" ../
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- I could not find the latex command.
-- I could not find the pdflatex command.
-- I could not find the htlatex command.
-- I could not find the bibtex command.
-- I could not find the biber command.
-- I could not find the makeindex command.
-- I could not find the dvips command.
-- I could not find the ps2pdf command.
-- I could not find the pdftops command.
-- USING MACHINE-SPECIFIC LINKER_FLAGS: -fopenmp
-- ENABLING OpenMP Implementation
-- DISABLING OpenMP Target Implementation
-- DISABLING OpenSHMEM Implementation
-- DISABLING MPI Implementation
-- DISABLING XBGAS Implementation
-- DISABLING Pthreads Implementation
-- DISABLING OpenACC Implementation
-- DISABLING OpenCL Implementation
-- DISABLING C++ Standard Atomics Implementation
-- CT_INCLUDE_PATH set to /global/home/users/brodyw/circustent/include
-- CT_SRC_PATH set to /global/home/users/brodyw/circustent/src/CircusTent
-- Configuring done
-- Generating done
-- Build files have been written to: /global/home/users/brodyw/circustent/build
[brodyw@tessa003 build]$ make
[ 20%] Building CXX object src/CircusTent/Impl/CT_OMP/CMakeFiles/CT_OMP_OBJS.dir/CT_OMP.cpp.o
[ 40%] Building C object src/CircusTent/Impl/CT_OMP/CMakeFiles/CT_OMP_OBJS.dir/CT_OMP_IMPL.c.o
[ 40%] Built target CT_OMP_OBJS
[ 60%] Building CXX object src/CircusTent/CMakeFiles/circustent.dir/CT_Main.cpp.o
[ 80%] Building CXX object src/CircusTent/CMakeFiles/circustent.dir/CTOpts.cpp.o
[100%] Linking CXX executable circustent
[100%] Built target circustent
[brodyw@tessa003 build]$

**Comment by jleidel** [comment]
why doesn't the cmake link do this automatically?

**Comment by BrodyWilliams** [comment]
Previously, it would do so because we added “-fopenmp” to the flags by default in the top-level CMakeLists.txt file whenever -DENABLE_OMP was specified. The downside of course was the user would have to edit CMakeLists if they wanted to use something like the intel compiler.

Originally, I also had similar hard-wired flags for the offloading backends which caused issues when I was testing with icx/icpx and nvc/nvc++.

On Oct 21, 2022, at 8:54 PM, jleidel ***@***.***> wrote:

﻿

why doesn't the cmake link do this automatically?

**Pull request merged**
